version: '3' 
services:
  simple_blog_api:
      depends_on:
        - postgres-db
      build: 
        context: ./
        dockerfile: Dockerfile
      image: ramanathannatarajan/simpleblog
      ports:
          - "3000:3000"
      environment:
        - POSTGRES_HOST=postgres-db
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
    # postgres database
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
